"""empty message

Revision ID: 7fcadf264bde
Revises: fc36b6c410fa
Create Date: 2021-11-26 19:50:21.093337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcadf264bde'
down_revision = 'fc36b6c410fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_key', sa.String(), nullable=True))
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cart', 'product_key')
    # ### end Alembic commands ###
